trigger:
- main

variables:
  azureSubscription: 'Azure subscription 1(1c29d824-9aa5-4286-9b2e-161e891c333f)'
  webAppName: 'reacttest1'

pool:
  name: Default

stages:

# =========================
# BUILD STAGE
# =========================
- stage: Build
  displayName: 'Build React App'
  jobs:
  - job: Build
    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Install dependencies & build'
      workingDirectory: '$(Build.SourcesDirectory)' 
    - script: |
    echo "===== ROOT DIRECTORY ====="
    dir $(Build.SourcesDirectory)
    echo "===== RECURSIVE LIST ====="
    dir $(Build.SourcesDirectory) /s
  displayName: 'DEBUG: Show folder structure'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)\build'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/react-build.zip'
        replaceExistingArchive: true
  
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'

# =========================
# DEPLOY STAGE
# =========================
- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  jobs:
  - deployment: DeployReact
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/drop/react-build.zip'

